version: "3.8"

services:
  redis:
    image: 'redis:6.0'
    container_name: redis-demo
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mysql:
    image: mysql:8.0
    container_name: mysql-demo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: demo

  mongo:
    image: mongo
    container_name: mongo-demo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mysql-data:
  redis-data: